### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [teekaytech/Restaurant-Page#2]
Hello Taofeek :wave: 
Thanks for your presentation :blush: 

In the Page class, you have methods that are creating a variable and returning that variable. Since there are no other operations in those methods, you can immediately return the single operations in those methods :blush: 

With all my respect :pray:

**Comment by mariosknl** [comment]
Great project Taofeek. I liked the way you have structured your project.

**Comment by teekaytech** [comment]
> Hello Taofeek 
> Thanks for your presentation 
> 
> In the Page class, you have methods that are creating a variable and returning that variable. Since there are no other operations in those methods, you can immediately return the single operations in those methods 
> 
> With all my respect

Thank you. I'll surely into it.
